---
environment: production
chdir: /www/projects/sinatra-hello-world
address: 127.0.0.1
port: 8910
pid: /www/projects/sinatra-hello-world/integrity.pid
rackup: /www/projects/sinatra-hello-world/configs/integrity.ru
log: /www/projects/sinatra-hello-world/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
servers: 1